USE azpz;

DELETE from projects;

INSERT Into projects (text, start, timestamp) VALUES
('Projekt 1',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('Projekt 2',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('Projekt 3',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('Projekt 4',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('Projekt 5',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('Projekt 6',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
;

